// ─────────────────────────────────────────────────────────────────────────────
// Prisma Client — singleton pattern for Next.js dev hot-reloading
// NOTE: PrismaClient is generated by "npx prisma generate".
// ─────────────────────────────────────────────────────────────────────────────
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const db =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.PRISMA_QUERY_LOGS === "true"
        ? ["query", "error", "warn"]
        : ["error", "warn"],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = db;
